### PR TITLE
Updated Menus

### PR DESCRIPTION
**Pull request by XuanHanTan-Work**
Updates include:
- Added option for outlined and disabled menu button
- Added description text support for MenuItem
- Added leading and trailing components for MenuItem

包括：
- 在菜单按钮加上了轮廓和禁用按钮的选择
- 在 MenuItem 中加上说明属性
- 在 MenuItem 中加上前后组件属性

### CODE REVIEW

**Review by xiaodanyang — COMMENTED** [review]
Review code KPI.

**Comment by XuanHanTan-Work** [comment]
Is there an estimate of when the next release will be published on NPM?

**Comment by lerte** [comment]
0.1.69 already published

**Comment by XuanHanTan-Work** [comment]
Great, thank you. But I think the docs website has not been updated yet.

**Comment by XuanHanTan-Work** [comment]
Nevermind, it was my browser cache. The website is indeed updated.

**Pull request merged**
